---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.app.namespace }}
  annotations:
    {{- include "rhcl.syncWave" "0" | nindent 4 }}
  labels:
    {{- include "rhcl.rhdpLabel" . | nindent 4 }}
