{{- if eq .Values.gatewayProvider "istio" }}
---
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
  annotations:
    {{- include "rhcl.syncWave" "10" | nindent 4 }}
spec:
  namespace: istio-system
  updateStrategy:
    type: InPlace
{{- end }}
