{{- if eq .Values.gatewayProvider "istio" }}
---
apiVersion: sailoperator.io/v1
kind: IstioCNI
metadata:
  name: default
  annotations:
    {{- include "rhcl.syncWave" "10" | nindent 4 }}
spec:
  namespace: istio-cni
{{- end }}
