{{- if .Values.keycloak.enabled }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: {{ .Values.keycloak.namespace }}
  annotations:
    {{- include "rhcl.syncWave" "15" | nindent 4 }}
spec:
  instances: {{ .Values.keycloak.instances }}
  http:
    httpEnabled: true
  hostname:
    strict: false
  proxy:
    headers: xforwarded
{{- end }}
