{{- if .Values.policies.globalRateLimit }}
---
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: global-ratelimit
  namespace: {{ include "rhcl.gatewayNamespace" . }}
  annotations:
    {{- include "rhcl.syncWave" "30" | nindent 4 }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: workshop-gateway
  defaults:
    limits:
      global:
        rates:
          - limit: {{ .Values.policies.globalRateLimitRate }}
            window: {{ .Values.policies.globalRateLimitWindow }}
{{- end }}
