{{- if .Values.policies.jwtAuth }}
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: jwt-auth
  namespace: {{ .Values.app.namespace }}
  annotations:
    {{- include "rhcl.syncWave" "30" | nindent 4 }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ .Values.app.name }}
  rules:
    authentication:
      keycloak-jwt:
        jwt:
          issuerUrl: {{ include "rhcl.keycloakUrl" . }}/realms/{{ .Values.keycloak.realm.name }}
        credentials:
          authorizationHeader:
            prefix: Bearer
{{- end }}
