{{- if .Values.policies.overrides }}
---
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: override-ratelimit
  namespace: {{ include "rhcl.gatewayNamespace" . }}
  annotations:
    {{- include "rhcl.syncWave" "30" | nindent 4 }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: workshop-gateway
  overrides:
    limits:
      global:
        rates:
          - limit: {{ .Values.policies.overridesRate }}
            window: {{ .Values.policies.overridesWindow }}
{{- end }}
