---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: workshop-gateway
  namespace: {{ include "rhcl.gatewayNamespace" . }}
  annotations:
    {{- include "rhcl.syncWave" "20" | nindent 4 }}
  labels:
    kuadrant.io/gateway: "true"
    {{- include "rhcl.rhdpLabel" . | nindent 4 }}
spec:
  gatewayClassName: {{ include "rhcl.gatewayClassName" . }}
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: {{ include "rhcl.gatewayHostname" . | quote }}
      allowedRoutes:
        namespaces:
          from: All
